---
AllCops:
  TargetRubyVersion: 2.5.1
  Include:
    - 'Gemfile'
    - 'Rakefile'
    - 'app/**/*.rb'
  Exclude:
    #- '_snippets/**/*.rb'
    - '_*/**/*'

# ignore block length in non-production code
Metrics/BlockLength:
  Enabled: true
  Exclude:
    - spec/**/*
    - Rakefile
    - app/controllers/**/*.rb

# allow unsafe YAML loading in non-production code
Security/YAMLLoad:
  Enabled: true
  Exclude:
    - spec/**/*

Style/HashSyntax:
  Enabled: true
  Exclude: 
    - Rakefile

Style/SymbolArray:
  Enabled: true
  Exclude: 
    - Rakefile
    - app/infrastructure/database/migrations/*.rb

Layout/MultilineMethodCallIndentation:
  Enabled: true
  EnforcedStyle: indented
